//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL2ActiveDirectory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeOrganCharts = new HashSet<EmployeeOrganChart>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string CardId { get; set; }
        public string CreationFileDate { get; set; }
        public string PrimaryEmploymentDate { get; set; }
        public Nullable<long> Native_Id { get; set; }
        public Nullable<long> Religion_Id { get; set; }
        public string EMail { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<long> BloodType_Id { get; set; }
        public long CompanyType_Id { get; set; }
        public string FamilyCardId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<EmployeeOrganChart> EmployeeOrganCharts { get; set; }
    }
}
