//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL2ActiveDirectory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganChart
    {
        public OrganChart()
        {
            this.OrganChart1 = new HashSet<OrganChart>();
        }
    
        public long Id { get; set; }
        public Nullable<long> Job_Id { get; set; }
        public long Unit_Id { get; set; }
        public Nullable<long> OrganChart_Parent_Id { get; set; }
        public long PositionType_Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Date { get; set; }
        public Nullable<bool> KeepHistory { get; set; }
    
        public virtual ICollection<OrganChart> OrganChart1 { get; set; }
        public virtual OrganChart OrganChart2 { get; set; }
    }
}
