//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL2ActiveDirectory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string FatherName { get; set; }
        public string BirthDate { get; set; }
        public Nullable<long> City_Id { get; set; }
        public string IdNumber { get; set; }
        public string NationalCode { get; set; }
        public long Gender_Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Mobile { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
