//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL2ActiveDirectory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Unit1 = new HashSet<Unit>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<long> Unit_Parent_Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public bool IsManagement { get; set; }
    
        public virtual ICollection<Unit> Unit1 { get; set; }
        public virtual Unit Unit2 { get; set; }
    }
}
